# Generated by Django 3.2 on 2022-09-05 11:31

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexbox',
            fields=[
                ('class_name', models.CharField(max_length=80)),
                ('background_colour', models.CharField(blank=True, max_length=30, null=True)),
                ('colour', models.CharField(blank=True, max_length=30, null=True)),
                ('direction', models.CharField(blank=True, max_length=80, null=True)),
                ('wrap', models.CharField(blank=True, max_length=80, null=True)),
                ('justify_content', models.CharField(blank=True, max_length=80, null=True)),
                ('align_items', models.CharField(blank=True, max_length=80, null=True)),
                ('align_content', models.CharField(blank=True, max_length=80, null=True)),
                ('gap', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsflex_flexbox', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FlexItem',
            fields=[
                ('class_name', models.CharField(blank=True, max_length=80, null=True)),
                ('flex', models.CharField(blank=True, max_length=50, null=True)),
                ('align_self', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsflex_flexitem', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
