# Generated by Django 3.2 on 2022-10-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsflex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexbox',
            old_name='class_name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='flexitem',
            old_name='class_name',
            new_name='label',
        ),
    ]
