# Generated by Django 3.2 on 2022-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsflex', '0002_auto_20221009_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexbox',
            name='responsive',
            field=models.BooleanField(default=True),
        ),
    ]
